package oop09.exception;

public class ExceptionTest03 {
	public static void main(String[] args) {

		//throwException();

		System.out.println("종료");

	}
}
